CREATE TABLE IF NOT EXISTS Players (
	pname TEXT PRIMARY KEY,
	pdga INTEGER NOT NULL,
	FLO INTEGER,
	WACO INTEGER,
	AUSTN INTEGER, 
	TXSTS INTEGER, 
	JBO INTEGER, 
	MCO INTEGER, 
	DDO INTEGER, 
	OTB INTEGER, 
	PDXO INTEGER, 
	BSF INTEGER, 
	TPC INTEGER, 
	DMC INTEGER, 
	EO INTEGER,
    LSO INTEGER, 
	IDLE INTEGER, 
	WORLDS INTEGER, 
	DGLO INTEGER, 
	GMC INTEGER, 
	MVP INTEGER, 
	USDGC INTEGER
);

CREATE TABLE IF NOT EXISTS Users (
	uname TEXT PRIMARY KEY,
	pword PASSWORD NOT NULL,
	salt TEXT NOT NULL
);